// Asset manifest. Generated by asset-research agent.
// Sources:
//   - Picsum Photos (https://picsum.photos — free stock photo service,
//     no attribution required, always-available CDN).
//   - three-globe example assets (https://github.com/vasturiano/three-globe —
//     MIT-licensed; example imagery is NASA Visible Earth / public domain).
//   - Lucide icons (https://lucide.dev — ISC license, free for commercial use).
//
// Strategy: We use the Picsum Photos seeded endpoint
// (https://picsum.photos/seed/{seed}/{w}/{h}). The seed makes each hotel get
// a stable, deterministic image — same hotel always shows the same photo
// across page loads, which is what the comparison drawer needs.
//
// All entries below are PM-view-callable. V1 of the product would replace
// these with licensed/commissioned photography per hotel partner.

export const ASSETS = {
  // -------------------------------------------------------------------------
  // A. Hotel hero images — 10 marquee properties + extras for completeness.
  // Each hotel id is used as the Picsum seed for a stable image.
  // -------------------------------------------------------------------------
  hotelImages: {
    aria: {
      url: 'https://picsum.photos/seed/aria/800/600',
      alt: 'Luxury Las Vegas casino interior',
      credit: 'Picsum Photos',
    },
    venetian: {
      url: 'https://picsum.photos/seed/venetian/800/600',
      alt: 'Opulent Italian-style luxury hotel lobby',
      credit: 'Picsum Photos',
    },
    mgm: {
      url: 'https://picsum.photos/seed/mgm/800/600',
      alt: 'Modern Las Vegas casino resort exterior',
      credit: 'Picsum Photos',
    },
    wynn: {
      url: 'https://picsum.photos/seed/wynn/800/600',
      alt: 'High-end Strip hotel suite',
      credit: 'Picsum Photos',
    },
    linq: {
      url: 'https://picsum.photos/seed/linq/800/600',
      alt: 'Mid-tier Las Vegas hotel room',
      credit: 'Picsum Photos',
    },
    'nomad-lv': {
      url: 'https://picsum.photos/seed/nomad-lv/800/600',
      alt: 'Boutique vintage hotel bar',
      credit: 'Picsum Photos',
    },
    standard: {
      url: 'https://picsum.photos/seed/standard/800/600',
      alt: 'Modern Manhattan boutique hotel',
      credit: 'Picsum Photos',
    },
    soho: {
      url: 'https://picsum.photos/seed/soho/800/600',
      alt: 'SoHo boutique loft hotel',
      credit: 'Picsum Photos',
    },
    plaza: {
      url: 'https://picsum.photos/seed/plaza/800/600',
      alt: 'Classic luxury New York hotel ballroom',
      credit: 'Picsum Photos',
    },
    'pod-times': {
      url: 'https://picsum.photos/seed/pod-times/800/600',
      alt: 'Times Square modern hotel exterior',
      credit: 'Picsum Photos',
    },
    ace: {
      url: 'https://picsum.photos/seed/ace/800/600',
      alt: 'Boutique hipster minimal London hotel',
      credit: 'Picsum Photos',
    },
    savoy: {
      url: 'https://picsum.photos/seed/savoy/800/600',
      alt: 'Classic Edwardian London luxury hotel',
      credit: 'Picsum Photos',
    },
    shoreditch: {
      url: 'https://picsum.photos/seed/shoreditch/800/600',
      alt: 'London boutique Shoreditch hotel',
      credit: 'Picsum Photos',
    },
    'park-paris': {
      url: 'https://picsum.photos/seed/park-paris/800/600',
      alt: 'Modern Paris luxury hotel suite',
      credit: 'Picsum Photos',
    },
    'le-marais': {
      url: 'https://picsum.photos/seed/le-marais/800/600',
      alt: 'Le Marais Paris boutique hotel facade',
      credit: 'Picsum Photos',
    },
    'park-tokyo': {
      url: 'https://picsum.photos/seed/park-tokyo/800/600',
      alt: 'Minimalist Tokyo high-rise hotel',
      credit: 'Picsum Photos',
    },
    'hotel-okura': {
      url: 'https://picsum.photos/seed/hotel-okura/800/600',
      alt: 'Traditional Tokyo luxury hotel',
      credit: 'Picsum Photos',
    },
    burj: {
      url: 'https://picsum.photos/seed/burj/800/600',
      alt: 'Iconic Dubai luxury hotel exterior',
      credit: 'Picsum Photos',
    },
    rove: {
      url: 'https://picsum.photos/seed/rove/800/600',
      alt: 'Modern downtown Dubai hotel',
      credit: 'Picsum Photos',
    },
    fasano: {
      url: 'https://picsum.photos/seed/fasano/800/600',
      alt: 'Sydney harbor luxury hotel',
      credit: 'Picsum Photos',
    },
    'ace-bcn': {
      url: 'https://picsum.photos/seed/ace-bcn/800/600',
      alt: 'Barcelona boutique hotel in El Born',
      credit: 'Picsum Photos',
    },
  },

  // -------------------------------------------------------------------------
  // D. City hero strips — used as banners on filtered search results.
  // -------------------------------------------------------------------------
  cityHeroes: {
    'Las Vegas': {
      url: 'https://picsum.photos/seed/las-vegas/1200/300',
      alt: 'Las Vegas Strip at night',
      credit: 'Picsum Photos',
    },
    'New York': {
      url: 'https://picsum.photos/seed/new-york/1200/300',
      alt: 'New York Manhattan skyline',
      credit: 'Picsum Photos',
    },
    London: {
      url: 'https://picsum.photos/seed/london/1200/300',
      alt: 'London skyline along the Thames',
      credit: 'Picsum Photos',
    },
    Paris: {
      url: 'https://picsum.photos/seed/paris/1200/300',
      alt: 'Paris skyline with Eiffel Tower',
      credit: 'Picsum Photos',
    },
    Tokyo: {
      url: 'https://picsum.photos/seed/tokyo/1200/300',
      alt: 'Tokyo neon skyline',
      credit: 'Picsum Photos',
    },
    Dubai: {
      url: 'https://picsum.photos/seed/dubai/1200/300',
      alt: 'Dubai skyline with Burj Khalifa',
      credit: 'Picsum Photos',
    },
    Sydney: {
      url: 'https://picsum.photos/seed/sydney/1200/300',
      alt: 'Sydney Harbor and Opera House',
      credit: 'Picsum Photos',
    },
    Barcelona: {
      url: 'https://picsum.photos/seed/barcelona/1200/300',
      alt: 'Barcelona skyline with Gaudí architecture',
      credit: 'Picsum Photos',
    },
  },

  // -------------------------------------------------------------------------
  // B (cont). Globe textures — alternates from three-globe examples.
  // BSD/MIT licensed; underlying imagery is NASA Visible Earth (public domain).
  // -------------------------------------------------------------------------
  globeTextures: {
    blueMarble: 'https://unpkg.com/three-globe/example/img/earth-blue-marble.jpg',
    night:      'https://unpkg.com/three-globe/example/img/earth-night.jpg',
    day:        'https://unpkg.com/three-globe/example/img/earth-day.jpg',
    water:      'https://unpkg.com/three-globe/example/img/earth-water.png',
    topology:   'https://unpkg.com/three-globe/example/img/earth-topology.png',
    nightSky:   'https://unpkg.com/three-globe/example/img/night-sky.png',
  },

  // -------------------------------------------------------------------------
  // C. Agent icons — lucide-react component names. The implementation step
  // can `import { Bird, Compass, Moon } from 'lucide-react'`.
  // -------------------------------------------------------------------------
  agentIcons: {
    hawk: 'Bird',     // sharp, fast — best fit for a hunter agent
    sage: 'Compass',  // precise navigation — best fit for a planner agent
    owl:  'Moon',     // night/last-minute — best fit for the late-deals agent
  },

  // -------------------------------------------------------------------------
  // B. Brand assets — favicon and Open Graph hero.
  // -------------------------------------------------------------------------
  brand: {
    ogImage: {
      // 1200x630 is the canonical OG image size. Stable seed gives a
      // consistent skyline-style image across every share.
      url: 'https://picsum.photos/seed/agentexchange-og/1200/630',
      alt: 'AgentExchange — Smart hotel deals on autopilot',
      credit: 'Picsum Photos',
    },
    // Inline SVG favicon: stylized coral hawk-pin glyph. Ship as
    // public/favicon.svg and reference from index.html as
    // <link rel="icon" type="image/svg+xml" href="/favicon.svg" />.
    // Color #FF6B5B matches the AgentExchange coral accent.
    faviconSvg:
      `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="#FF6B5B" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2 L4 9 L7 9 L7 21 L17 21 L17 9 L20 9 Z" fill="#FF6B5B" fill-opacity="0.15"/><circle cx="12" cy="13" r="2.5" fill="#FF6B5B"/></svg>`,
  },
}

export default ASSETS
